// src/hooks/useIndividuals.js — MERGE FIX: same auth import path change as useHouseholds.js.
import { useEffect, useState, useCallback } from "react";
import {
  collection, onSnapshot, addDoc, setDoc, updateDoc, deleteDoc, doc, serverTimestamp, query, where, orderBy,
} from "firebase/firestore";
import { db } from "../lib/firebase";
import { useToast } from "../contexts/ToastContext";
import { useAuth } from "./usePermissions";
import { logActivity } from "../lib/activityLog";
import { toMonthDay } from "../lib/dateHelpers";
import { friendlyFirestoreError } from "../lib/firestoreErrorMessage";

export function useIndividuals(householdId) {
  const [individuals, setIndividuals] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);
  const { showToast } = useToast();
  const { volunteer } = useAuth();

  useEffect(() => {
    if (!householdId) { setIndividuals([]); setLoading(false); return; }
    setLoading(true);
    const q = query(collection(db, "individuals"), where("householdId", "==", householdId), orderBy("isPrimary", "desc"));
    const unsub = onSnapshot(
      q,
      (snap) => { setIndividuals(snap.docs.map((d) => ({ id: d.id, ...d.data() }))); setLoading(false); },
      (err) => { console.error(err); setError(err); setLoading(false); showToast({ type: "error", message: friendlyFirestoreError(err, "family members") }); }
    );
    return unsub;
  }, [householdId, showToast]);

  const withDerivedFields = (data) => ({
    ...data,
    dobMonthDay: data.dob !== undefined ? toMonthDay(data.dob) : undefined,
    anniversaryMonthDay: data.anniversary !== undefined ? toMonthDay(data.anniversary) : undefined,
  });

  const createIndividual = useCallback(
    async (data) => {
      // `id` may arrive pre-generated by IndividualForm (see draftId there) —
      // this lets a photo be uploaded to Storage under that id *before* the
      // Firestore doc exists, so "add photo on first-time add" works. When
      // present we setDoc to that id instead of letting addDoc pick one.
      const { id: presetId, ...rest } = data;
      const tempId = presetId || `temp-${Date.now()}`;
      const payload = withDerivedFields({ ...rest, householdId });
      const optimisticDoc = { id: tempId, ...payload, createdAt: new Date(), updatedAt: new Date(), _pending: true };
      setIndividuals((prev) => [...prev, optimisticDoc]);
      try {
        let newId;
        if (presetId) {
          await setDoc(doc(db, "individuals", presetId), { ...payload, createdAt: serverTimestamp(), updatedAt: serverTimestamp() });
          newId = presetId;
        } else {
          const ref = await addDoc(collection(db, "individuals"), { ...payload, createdAt: serverTimestamp(), updatedAt: serverTimestamp() });
          newId = ref.id;
        }
        setIndividuals((prev) => prev.map((i) => (i.id === tempId ? { ...i, id: newId, _pending: false } : i)));
        logActivity({ volunteerId: volunteer?.id, individualId: newId, action: "create_individual" });
        showToast({ type: "success", message: `${data.name || "Member"} added.` });
        return newId;
      } catch (err) {
        console.error(err);
        setIndividuals((prev) => prev.filter((i) => i.id !== tempId));
        showToast({ type: "error", message: "Couldn't save the family member. Try again." });
        return null;
      }
    },
    [householdId, showToast, volunteer]
  );

  const updateIndividual = useCallback(
    async (id, data) => {
      const previous = individuals.find((i) => i.id === id);
      const payload = withDerivedFields(data);
      setIndividuals((prev) => prev.map((i) => (i.id === id ? { ...i, ...payload, updatedAt: new Date() } : i)));
      try {
        await updateDoc(doc(db, "individuals", id), { ...payload, updatedAt: serverTimestamp() });
        logActivity({ volunteerId: volunteer?.id, individualId: id, action: "update_individual", details: { fields: Object.keys(data) } });
        showToast({ type: "success", message: "Details updated." });
        return true;
      } catch (err) {
        console.error(err);
        if (previous) setIndividuals((prev) => prev.map((i) => (i.id === id ? previous : i)));
        showToast({ type: "error", message: "Couldn't save changes. Reverted." });
        return false;
      }
    },
    [individuals, showToast, volunteer]
  );

  const deleteIndividual = useCallback(
    async (id) => {
      const previous = individuals.find((i) => i.id === id);
      const previousIndex = individuals.findIndex((i) => i.id === id);
      setIndividuals((prev) => prev.filter((i) => i.id !== id));
      try {
        await deleteDoc(doc(db, "individuals", id));
        logActivity({ volunteerId: volunteer?.id, individualId: id, action: "delete_individual" });
        showToast({ type: "success", message: "Member removed." });
        return true;
      } catch (err) {
        console.error(err);
        if (previous) setIndividuals((prev) => { const next = [...prev]; next.splice(previousIndex, 0, previous); return next; });
        showToast({ type: "error", message: "Couldn't remove the member. Restored." });
        return false;
      }
    },
    [individuals, showToast, volunteer]
  );

  return { individuals, loading, error, createIndividual, updateIndividual, deleteIndividual };
}
